### ISSUE TITLE
Support for Candy library

### ISSUE THREAD

**Issue by fermartz** [Gekctek/motoko_candid#5]
First of all thanks for creating this library. 

motoko_candid has helped me a lot 🙌 . 

Are you planning to support [candy library](https://github.com/icdevs/candy_library)?

I tried to add it myself but I got a bit confused when decoding returns #recursiveType... am I on the right track? 😬

**Comment by Gekctek** [comment]
I can look into it but I'm only vaguely familiar with that library. You are looking to just convert between the types?

Recursive types are self/cyclical referencing types like a box record had a box type for one of its fields

**Comment by Gekctek** [comment]
@fermartz

**Comment by fermartz** [comment]
@Gekctek 🖐️ 
The final goal is to stringify any candid value, which I already accomplish with motoko_candid help. [Take a look here](https://github.com/ORIGYN-SA/candid_stringify/blob/main/src/candid_stringify.mo)
However, sometimes within the candid data we have a candy value, which motoko_candid do not recognize.

So, in few words I'm trying to convert any candid value to text. You can take a look at [this example in the Motoko playground](https://m7sm4-2iaaa-aaaab-qabra-cai.raw.ic0.app/?tag=627830390).

Thanks for the help 🙌

**Comment by Gekctek** [comment]
@fermartz Im so sorry, this somehow dropped off my todo list

So i took a look at the examples and the candy library
Im not clear on what the solution is. It seems like the candy library values would come in a be printed as a variant. But you want it what it actually represents? Can you give me an example
If I understand, Im not sure exactly what I can do. The Candy library is defining types and but Candy isnt an official motoko thing and since motoko is structurally typed vs class/classic typing, so there would be nothing special about candy types. What I could? do is add a to_string method like you have and have overrides for custom data structures, so that if a type matches a custom defined one, it would use the override to_string method vs the default candid one. Does that sound like its helpful? I can do a little more digging but just want to make sure we are on the same page

**Comment by fermartz** [comment]
@Gekctek thank you so much for your help 🙏 .

Your solution sounds good but I'm still unable to understand what you are going to return if the input value is a Candy value? Would you be able to override to_string as well?

**Comment by skilesare** [comment]
That would be fairly interesting, because you should be able to convert basic candy into candid equivalence and compare the hash signatures of the object types. I'm not quite sure what this gets us, but Fernandez been working on it really closely and knows what he has in mind.  If I recall the whole point of this is to try to make our logs look a little bit prettier. Fernando, it might be worthwhile to post how the logs are currently coming out, and then how you would expect them to come out after we finish this work.

**Comment by Gekctek** [comment]
looking at it, the options i see are add an optional resolver function like `(type:Type,value:Value) -> Text` or an optional type mapping to declare what custom types map to what custom string `TrieMap.TrieMap<Type, (value: Value) -> Text>`. So if you wanted to do the candy types as a custom output you could define the equivalent candid `Type` of the candy library, and how you want to tranform the value. This would keep the libraries decoupled but to be able to do what you want.
Does that sound like it would work for you? i could code something up tommorrow

**Comment by fermartz** [comment]
Fer MartzOn Feb 3, 2023, at 12:31 AM, Ethan Celletti ***@***.***> wrote:﻿
looking at it, the options i see are add an optional resolver function like (type:Type,value:Value) -> Text or an optional type mapping to declare what custom types map to what custom string TrieMap.TrieMap<Type, (value: Value) -> Text>. So if you wanted to do the candy types as a custom output you could define the equivalent candid Type of the candy library, and how you want to tranform the value. This would keep the libraries decoupled but to be able to do what you want.
Does that sound like it would work for you? i could code something up tommorrow

**Comment by fermartz** [comment]
@Gekctek It sounds like the second option would do the trick but if is not too much work also including the first option feels like it would be very helpful.

Thanks for all the help, I really appreciate it 🙏

**Comment by Gekctek** [comment]
@fermartz try out candid 1.0.0 on MOPS. is good to go

**Comment by fermartz** [comment]
@Gekctek 
Awesome...will do. 
I've been tied up with another task but I'll be working on this one next week.

Thanks again!!!
